imports:
    - { resource: parameters.yml }

doctrine:
    dbal:
        #To counter the error caused by 'mapping_types'
        connections:
            default:
                server_version: %database_server_version%
                mapping_types:
                    set: string
        types:
            PermissionLevels: Dtf\General\SassBundle\Core\AccessControl\PermissionLevels
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"
