<?php

namespace Dtf\General\SaasBundle\Repository;

/**
 * TelephoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelephoneRepository extends \Doctrine\ORM\EntityRepository
{
}
