<?php

namespace Dtf\General\SaasBundle\Repository;

/**
 * AccessControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessControlRepository extends \Doctrine\ORM\EntityRepository
{
}
