<?php

namespace Dtf\General\SaasBundle\Repository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends \Doctrine\ORM\EntityRepository
{
    use LogMetaDataRepositoryTrait, StatusRepositoryTrait;
}
