<?php

namespace Dtf\General\SaasBundle\Repository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    use LogMetaDataRepositoryTrait, StatusRepositoryTrait;
}
