dtf_general_contact_management:
    resource: "@DtfGeneralContactManagementBundle/Controller/"
    type:     annotation
    prefix:   /

dtf_general_user_management:
    resource: "@DtfGeneralUserManagementBundle/Controller/"
    type:     annotation
    prefix:   /

sass:
    resource: "@SaasBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
