dtf_general_contact_management:
    resource: "@ContactManagementBundle/Resources/config/routing.yml"
    prefix:   /

dtf_general_user_management:
    resource: "@UserManagementBundle/Resources/config/routing.yml"
    prefix:   /

sass:
    resource: "@SaasBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
