Dtf\General\SassBundle\Entity\AccessControl:
    type: entity
    table: null
    repositoryClass: Dtf\General\SassBundle\Repository\AccessControlRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        modelId:
            type: integer
            column: model_id
        modelClass:
            type: string
            length: 100
            column: model_class
        permissionLevels:
            type: Dtf\General\SassBundle\Core\AccessControl\PermissionLevels
            column: permission_levels
        everyone:
            type: boolean
        accountId:
            type: integer
            column: account_id
        propagateToSubAccounts:
            type: boolean
            column: propagate_to_sub_accounts
        roleId:
            type: integer
            column: role_id
        userId:
            type: integer
            column: user_id
        createUserId:
            type: integer
            column: create_user_id
        updateUserId:
            type: integer
            column: update_user_id
        createTime:
            type: integer
            column: create_time
        updateTime:
            type: integer
            column: update_time
    lifecycleCallbacks: {  }
