Dtf\General\SassBundle\Entity\Address:
    type: entity
    table: null
    repositoryClass: Dtf\General\SassBundle\Repository\AddressRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: 100
        line1:
            type: string
            length: 100
        line2:
            type: string
            length: 100
        line3:
            type: string
            length: 100
        postCode:
            type: string
            length: 100
            column: post_code
        city:
            type: string
            length: 100
        region:
            type: string
            length: 100
        countryId:
            type: integer
            column: country_id
        details:
            type: text
    lifecycleCallbacks: {  }
