Dtf\General\SassBundle\Entity\Person:
    type: entity
    table: null
    repositoryClass: Dtf\General\SassBundle\Repository\PersonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        first_name:
            type: string
            length: 100
        middle_name:
            type: string
            length: 100
        last_name:
            type: string
            length: 100
        hair_color:
            type: string
            length: 20
        eye_color:
            type: string
            length: 20
        height:
            type: integer
        height_unit:
            type: string
            length: 20
        weight:
            type: integer
        weight_unit:
            type: string
            length: 20
        date_of_birth:
            type: datetime
        ethnicity:
            type: string
            length: 50
        gender:
            type: string
            length: 20
    lifecycleCallbacks: {  }
