Dtf\General\SassBundle\Entity\Telephone:
    type: entity
    table: null
    repositoryClass: Dtf\General\SassBundle\Repository\TelephoneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        typeId:
            type: smallint
        number:
            type: string
            length: 30
    lifecycleCallbacks: {  }
