<?php

namespace Dtf\General\SassBundle\Repository;

/**
 * TelephoneTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelephoneTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
