Dtf\General\SaasBundle\Entity\TelephoneType:
    type: entity
    table: null
    repositoryClass: Dtf\General\SaasBundle\Repository\TelephoneTypeRepository
    id:
        id:
            type: smallint
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 30
    lifecycleCallbacks: {  }
