Dtf\General\SaasBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Dtf\General\SaasBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 100
        passwordHash:
            type: string
            length: 100
            column: password_hash
        passwordSalt:
            type: string
            length: 100
            column: password_salt
        status:
            type: integer
        email:
            type: string
            length: 254
        createTime:
            type: integer
            column: create_time
        updateTime:
            type: integer
            column: update_time
        createUserId:
            type: integer
            column: create_user_id
        updateUserId:
            type: integer
            column: update_user_id
    lifecycleCallbacks: {  }
